
clean:
	rm -f *.o *.elf *.self *.48* *.bin *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o

all:
	rm -f *.o *.elf *.self *.48* *.bin *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	make -f Makefile_487C --no-print-directory

	#rm -f *.o *.elf *.self *.48* *.bin *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	#make -f Makefile_487D --no-print-directory

	#rm -f *.o *.bin *.elf *.48* *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	#rm -f *.o *.elf *.self ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
